# Generated by Django 5.0.2 on 2026-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='company_activity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نشاط الشركة'),
        ),
    ]
