# Generated by Django 5.0.2 on 2026-02-26 18:43

import django.db.models.deletion
import json.encoder
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.JSONField(encoder=json.encoder.JSONEncoder, verbose_name='القيمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('post', 'ترحيل'), ('cancel', 'إلغاء'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج')], max_length=20, verbose_name='نوع العملية')),
                ('model_name', models.CharField(max_length=100, verbose_name='اسم النموذج')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='تمثيل الكائن')),
                ('old_data', models.JSONField(blank=True, encoder=json.encoder.JSONEncoder, null=True, verbose_name='البيانات القديمة')),
                ('new_data', models.JSONField(blank=True, encoder=json.encoder.JSONEncoder, null=True, verbose_name='البيانات الجديدة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='وكيل المستخدم')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل مراجعة',
                'verbose_name_plural': 'سجلات المراجعة',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم السنة المالية')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشطة')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مغلقة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL, verbose_name='أغلقت بواسطة')),
            ],
            options={
                'verbose_name': 'سنة مالية',
                'verbose_name_plural': 'السنوات المالية',
                'ordering': ['-start_date'],
            },
        ),
    ]
