# Generated by Django 5.0.2 on 2026-02-27 18:01

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='رقم الحساب الفريد (مثال: 1، 1.1، 1.1.1)', max_length=20, unique=True, verbose_name='رقم الحساب')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق الملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], help_text='تصنيف الحساب المحاسبي', max_length=20, verbose_name='نوع الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_header', models.BooleanField(default=False, help_text='الحسابات الرئيسية لا يمكن استخدامها في القيود', verbose_name='حساب رئيسي')),
                ('allow_manual_entry', models.BooleanField(default=True, help_text='هل يمكن إدخال قيود يدوية على هذا الحساب', verbose_name='يسمح بالقيود اليدوية')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الرصيد الافتتاحي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='يتم تحديثه تلقائياً من القيود', max_digits=18, verbose_name='الرصيد الحالي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.account', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'شجرة الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(help_text='رقم القيد التسلسلي', max_length=50, unique=True, verbose_name='رقم القيد')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.TextField(help_text='وصف القيد أو سببه', verbose_name='الوصف')),
                ('reference', models.CharField(blank=True, help_text='رقم المرجع (فاتورة، أمر شراء، إلخ)', max_length=100, null=True, verbose_name='المرجع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي المدين')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الدائن')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='سبب الإلغاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='ألغي بواسطة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='core.fiscalyear', verbose_name='السنة المالية')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_posted', to=settings.AUTH_USER_MODEL, verbose_name='رحل بواسطة')),
            ],
            options={
                'verbose_name': 'قيد محاسبي',
                'verbose_name_plural': 'القيود المحاسبية',
                'ordering': ['-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='دائن')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوصف')),
                ('cost_center', models.CharField(blank=True, max_length=50, null=True, verbose_name='مركز التكلفة')),
                ('account', models.ForeignKey(limit_choices_to={'is_active': True, 'is_header': False}, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='core.account', verbose_name='الحساب')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.journalentry', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'بند قيد',
                'verbose_name_plural': 'بنود القيود',
                'ordering': ['id'],
            },
        ),
    ]
